### PR TITLE
UI refactor

### PR DESCRIPTION
**Pull request by nsmela**
Redesigned the app to have an easier time understanding the flow. Also resolved some nagging issues.

#102 
#87
#86 
#56

### CODE REVIEW

**Comment by michaelwkudla** [comment]
I sent this message in teams, but then realized it should probably be here. 
The refactor looks good! I'm not sure it's clinically useable yet though. 
I'm happy to have it be the "main" branch now and only make edits to the new one, but maybe we should make a backup-main branch of the current main branch? Perhaps calling it 0.3.0-Alpha-Main-Backup or something like that? Or maybe we should wait until it's clinically better to make it the "main" branch. LMK what you think! I'd love to video chat and have you go through the changes with me. 
 
Some ui-refactor issues I noticed: 

- [ ] On the cylinder tab, the opacity gets changed to 100% when you "apply settings"
- [ ] The checkbox says "Checkbox" 
- [ ] The channels diameter doesn't change when you click apply, and if you go to a different tab and back, it's reset to 3
- [ ] "Points" on the Channel details section of channel tab is kinda pointless. Don't even need the "Channel Details" box. Just the two buttons is perfect, and cleaner. Similar to how the tandem tab has it.
- [ ] Tandem comes in to high. and rotated 90 off from the tandem needle. 
- [ ] A tandem radius option will be needed. 
- [ ] If I change the needle length on Export, the reference sheet doesn't update. 
- [ ] Tandem import works, but then nothing shows up on the export screen, and the export doesn't work.
- [ ] Tandem doesn't show on ref sheet (ideally on map and list)
- [ ] Tandem shouldn't have an IS length or protruding length on sheet (N/A)
- [ ] Export needs to be the blue color of the other tabs.

**Comment by nsmela** [comment]
> I sent this message in teams, but then realized it should probably be here. The refactor looks good! I'm not sure it's clinically useable yet though. I'm happy to have it be the "main" branch now and only make edits to the new one, but maybe we should make a backup-main branch of the current main branch? Perhaps calling it 0.3.0-Alpha-Main-Backup or something like that? Or maybe we should wait until it's clinically better to make it the "main" branch. LMK what you think! I'd love to video chat and have you go through the changes with me.
> 
> Some ui-refactor issues I noticed:
> 
> * [x]  On the cylinder tab, the opacity gets changed to 100% when you "apply settings"
> * [x]  The checkbox says "Checkbox"
> * [x]  The channels diameter doesn't change when you click apply, and if you go to a different tab and back, it's reset to 3
> * [x]  "Points" on the Channel details section of channel tab is kinda pointless. Don't even need the "Channel Details" box. Just the two buttons is perfect, and cleaner. Similar to how the tandem tab has it.
> * [ ]  Tandem comes in to high. and rotated 90 off from the tandem needle.
         unable to reproduce
> * [ ]  A tandem radius option will be needed.
         tandem channel diameter is this value
> * [x]  If I change the needle length on Export, the reference sheet doesn't update.
> * [ ]  Tandem import works, but then nothing shows up on the export screen, and the export doesn't work.
         not being shown is by design, but unable to reproduce "export doesn't work" maybe we're using different files for the imported tandem
> * [ ]  Tandem doesn't show on ref sheet (ideally on map and list)
         that's something I was going to leave for you
> * [ ]  Tandem shouldn't have an IS length or protruding length on sheet (N/A)
         that's something I was going to leave for you
> * [x]  Export needs to be the blue color of the other tabs.

**Comment by nsmela** [comment]
Central axis added. Please review it to see if it's okay. I don't have a dataset to test with

fileio.py -> load)dicom_data was refactored. The central axis, the cylinder contour, and the channels were removed to be their own functions to make editing and reading easier. The central axis and cylinder contours both result in saving their results in DicomData.cylinder_tip, base and diameter. that way, loading the cylinder doesn't care if the central axis or contour was imported, but the results

**Comment by nsmela** [comment]
tandem can now be shown on export view

**Pull request merged**
